In [1]:
# Install packages
!pip install faiss-cpu
!pip install sentence-transformers

In [2]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)

In [3]:
df = pd.read_csv('sample_text.csv')
df.shape

(8, 2)

In [4]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [5]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

C:\Users\shaha\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(8, 768)

In [6]:
vectors

array([[-0.00247395,  0.03626721, -0.05290459, ..., -0.09152356,
        -0.03970002, -0.04330488],
       [-0.03357267,  0.00980517, -0.03250129, ..., -0.05165467,
         0.02245886, -0.03156182],
       [-0.01865323, -0.04051314, -0.01235387, ...,  0.00610585,
        -0.07179647,  0.02773853],
       ...,
       [-0.00066458,  0.04252125, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357664],
       [-0.03317154,  0.03252455, -0.02484838, ...,  0.01174421,
         0.05747123,  0.00571021],
       [-0.00166393,  0.00413829, -0.04597083, ...,  0.02008528,
         0.05656242, -0.00161596]], dtype=float32)

In [7]:
dim = vectors.shape[1]
dim

768

In [8]:
# this is index using Euclidean Distance
import faiss

index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000011E46641EF0> >

In [9]:
index.add(vectors)

In [10]:
search_query = "I want to buy a polo t-shirt"

vec = encoder.encode(search_query)
vec.shape

(768,)

In [11]:
vec

array([ 1.03882737e-02,  2.78686322e-02, -1.18618747e-02,  1.81327257e-02,
        1.21983129e-03, -1.42995678e-02,  1.96229350e-02,  2.07198095e-02,
       -2.23660525e-02,  4.75626774e-02,  1.77976117e-02, -8.00333917e-03,
        2.53419485e-02,  5.26149310e-02,  8.44939332e-03, -1.63944382e-02,
        1.02661774e-02, -2.74856407e-02,  8.37067366e-02, -1.52885346e-02,
        1.67682767e-02, -3.97140812e-03, -2.74348501e-02,  5.02091646e-02,
       -8.36523063e-03, -4.74075489e-02,  2.36915741e-02, -1.01186512e-02,
       -2.82840487e-02,  7.94264767e-03,  4.21435833e-02, -4.19375300e-03,
       -1.91232339e-02, -3.12785394e-02,  1.24685050e-06, -1.04428194e-02,
       -2.19971202e-02, -8.66928175e-02, -1.88498793e-03, -2.54772324e-02,
       -9.72972158e-03,  7.93310329e-02, -3.55963409e-02, -3.05369555e-04,
       -1.12392055e-02, -3.88932340e-02,  5.49313948e-02,  1.35207996e-01,
       -8.19147378e-02,  1.18785035e-02, -9.01844818e-03,  1.92544367e-02,
       -2.82723419e-02, -

In [12]:
# vector expects 2dimension
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [16]:
distances, I = index.search(svec, k=2)
I

array([[3, 2]], dtype=int64)

In [ ]:
# These two are the rows similar to the search query
df.loc[I[0]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [ ]:
# This is a semantic search using the meaning not a exact keyword search
search_query

'I want to buy a polo t-shirt'